[build]
publish = "public_html"
command = "hugo --gc"

[context.production.environment]
HUGO_VERSION = "0.72.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

# Para usar un sobdominio cambia el nombre de custombranch por el nombre que tu rama personalizada
#[context.custombranch]
#command = "hugo --gc -b https://custombranch.doctorstake.network"

#[context.custombranch.environment]
#HUGO_VERSION = "0.72.0"
#HUGO_ENV = "development"
#HUGO_ENABLEGITINFO = "true"

[[headers]]
  # Enable CORS.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
